name: notaro_mobile
description: 'A new Flutter project.'
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  cupertino_icons: ^1.0.8
  dio: ^5.9.0
  flutter:
    sdk: flutter
  flutter_animate: ^4.5.2
  flutter_riverpod: ^3.0.3
  flutter_screenutil: ^5.9.3
  freezed_annotation: ^3.1.0
  go_router: ^17.0.0
  google_fonts: ^6.3.2
  intl: ^0.20.2
  json_annotation: ^4.9.0
  lucide_icons_flutter: ^3.1.6
  riverpod_annotation: ^3.0.3
  shared_preferences: ^2.5.3

  uuid: any
dev_dependencies:
  build_runner: ^2.10.4
  custom_lint: ^0.8.1
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
  freezed: ^3.2.3
  go_router_builder: ^4.1.1
  json_serializable: ^6.11.2
  riverpod_generator: ^3.0.3
  riverpod_lint: ^3.0.3

flutter:
  uses-material-design: true
