name: notaro_mobile
description: 'A hyper-lightweight, modern note-taking app.'
repository: https://github.com/astraen-dev/notaro
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  collection: ^1.19.1
  cupertino_icons: ^1.0.8
  dio: ^5.9.0
  flutter:
    sdk: flutter
  flutter_animate: ^4.5.2
  flutter_launcher_icons: ^0.14.4
  flutter_localizations:
    sdk: flutter
  flutter_native_splash: ^2.4.7
  flutter_riverpod: ^3.0.3
  flutter_screenutil: ^5.9.3
  freezed_annotation: ^3.1.0
  go_router: ^17.0.0
  google_fonts: ^6.3.2
  hooks_riverpod: ^3.0.3
  in_app_review: ^2.0.11
  intl: ^0.20.2
  intl_utils: ^2.8.12
  json_annotation: ^4.9.0
  lucide_icons_flutter: ^3.1.6
  package_info_plus: ^9.0.0
  riverpod_annotation: ^3.0.3
  share_plus: ^12.0.1
  shared_preferences: ^2.5.3
  shimmer: ^3.0.0
  uuid: any

dev_dependencies:
  build_runner: ^2.10.4
  custom_lint: ^0.8.1
  dart_pubspec_licenses: ^3.0.14
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
  freezed: ^3.2.3
  freezed_lint: ^0.0.12
  go_router_builder: ^4.1.1
  json_serializable: ^6.11.2
  remove_unused_localizations_keys: ^0.0.40
  riverpod_generator: ^3.0.3
  riverpod_lint: ^3.0.3

flutter:
  generate: true
  uses-material-design: true
flutter_intl:
  enabled: true
